# Generated by Django 3.0.5 on 2021-03-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200814_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
